<?php

/**
 * Implements hook_field_schema().
 */
function wwm_media_alter_field_schema($field) {
  switch ($field['type']) {
    case 'css_class':
      $columns = array(
        'value' => array(
          'type' => 'varchar',
          'length' => 255,
          'not null' => FALSE,
        ),
      );
      break;
  }
  return array(
    'columns' => $columns,
    'indexes' => array(
      'value' => array('value'),
    ),
  );
}
