<?php
/**
 * Implements hook_media_wysiwyg_token_to_markup_alter().
 */
function wwm_media_alter_media_wysiwyg_token_to_markup_alter(&$element, $tag_info, $settings) {
  
  $file = $tag_info['file'];
  if (!empty($settings['wysiwyg']) || empty($file) || 'image' != $file->type) {
    return;
  }
  $wrapper = entity_metadata_wrapper('file', $file);

  $style = $wrapper->field_alignment->value();

  if (!empty($style)) {
    $element['content']['#attributes']['class'][] = $style;
  }

  dpm($element);
  
  // $link = $wrapper->field_myimagelinkfield->value();
  // if (!empty($link['url'])) {
  //   $url = url($link['url']);
  //   $element['content']['file']['#prefix'] = sprintf('<a href="%s">', $url);
  //   $element['content']['file']['#suffix'] = '</a>';
  // }
}
